name: Site scanner

on:
  workflow_dispatch:

jobs:
  DAST-scan:
    name: DAST site scanner
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        CLUSTER_IP: [3.76.219.129]
        port: [31546, 31547]

    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          target: http://${{ matrix.CLUSTER_IP }}:${{ matrix.port}}
          artifact_name: zap_scan_${{ matrix.CLUSTER_IP }}_${{ matrix.port }}
